### ISSUE TITLE
Falla el postinst con update-alternatives de mate-terminal 

### ISSUE THREAD

**Issue by hectorsanchez** [HuayraLinux/huayra-desktop#10]
Al hacer un apt-get upgrade,  falla el postinst falla la siguiente línea

  # si esta mate-terminal, actualizamos las alternativas.
  if [ `update-alternatives --list x-terminal-emulator|grep /usr/bin/mate-terminal` ]; then
      update-alternatives --set x-terminal-emulator /usr/bin/mate-terminal;
  fi

 
En mi alternatives, tengo : update-alternatives --list x-terminal-emulator

/usr/bin/koi8rxterm
/usr/bin/lxterm
/usr/bin/mate-terminal
/usr/bin/mate-terminal.wrapper
/usr/bin/uxterm
/usr/bin/xterm

**Comment by ftoledo** [comment]
corregido en 19562bf9b599fafe141ae6bd50008e725cd706fc
