### ISSUE TITLE
Captura de pantalla: Colorea por error el area seleccionada

### ISSUE THREAD

**Issue by AgataGuma** [HuayraLinux/huayra-desktop#14]
![pantallazo](https://cloud.githubusercontent.com/assets/19228704/18914781/e3c7cecc-8564-11e6-809c-3b6c60746e97.png)

Si optas por "Seleccionar área a capturar" queda una marca anaranjada...

**Comment by ftoledo** [comment]
https://github.com/mate-desktop/mate-utils/issues/128

**Comment by iglosiggio** [comment]
Anda en la próxima versión de mate-screenshot
