### ISSUE TITLE
GUVCView

### ISSUE THREAD

**Issue by mblink77** [HuayraLinux/huayra-desktop#20]
GUVCView es muy dificil de usar, Chesse sería una mejor opción.

**Comment by iglosiggio** [comment]
Hola! actualmente está en desarrollo [huayra-cam](https://github.com/HuayraLinux/huayra-cam) para cumplir esa misma funcionalidad (aunque (cheese)[https://wiki.gnome.org/Apps/Cheese] es una muy buena alternativa).

Estaría bueno que pruebes ambos (hay un (deb)[http://repo-frontend.surge.sh/#/packages/torbellino/huayra-cam] en torbellino) y critiques para mejorar este desarrollo (sería lógico poner cheese si no huayra-cam no llega a cumplir las expectativas).

Dejo abierto porque es un punto piola para debatir :smiley:
