### ISSUE TITLE
Al agregar usuario -> archivos en particiones no ext4 no van a papelera

### ISSUE THREAD

**Issue by luuuciano** [HuayraLinux/huayra-desktop#22]
Como se puede ver por http://huayra.conectarigualdad.gob.ar/foro/index.php/topic,1723.msg6123.html#msg6123

Al agregar un usuario personal, como bien sugiere el tutorial inicial de huayra, el id cambia de 1000 a 1001, o lo que sea el caso, y entonces al intentar borrar archivos de particiones no ext4 (DATOS, RECURSOS, etc....) aparece un mensaje de que se borrará permanentemente, sin pasar a la papelera...

¿Existirá alguna forma de mejorar esto, que sea evitando editar el fstab?
¿Qué pasa si son varios usuarios en la net?

**Comment by ftoledo** [comment]
Esta solucionado en la veriones nuevas de caja
