### ISSUE TITLE
Script sin sentido?

### ISSUE THREAD

**Issue by iglosiggio** [HuayraLinux/huayra-desktop#24]
En `base/grub.d/50_huayra_color` se ejecuta un exec (builtin de `sh`) pero existe código luego de ésta línea.
https://github.com/HuayraLinux/huayra-desktop/blob/de80d6c6bae8b66b5f9751e2eeb11b6a18d899cf/base/etc/grub.d/50_huayra_color#L1-L6

Según el manpage de `dash` (el `sh` de debian por defecto hasta dónde recuerdo):
```
exec [command arg ...]
        Unless command is omitted, the shell process is replaced with
        the specified program (which must be a real program, not a
        shell builtin or function).  Any redirections on the exec
        command are marked as permanent, so that they are not undone
        when the exec command finishes.
```

**Comment by ftoledo** [comment]
No es sin sentido. Al ejecutar update-grub, se ejecutan cada uno de los script que estan dentro de /etc/grub.d y el output de cada uno se va agregando a la configuracion de grub en el archivo /boot/grub/grub.cfg.

Este script agrega desde la linea 3 de si mismo gracias a ese exec sino tendrias que hacer un echo de cada linea o el tipico cat <<EOF ... EOF.

Entonces te queda el archivo grub.cfg asi en esa parte: 

```
### BEGIN /etc/grub.d/30_uefi-firmware ###
### END /etc/grub.d/30_uefi-firmware ###

### BEGIN /etc/grub.d/40_custom ###
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
### END /etc/grub.d/40_custom ###

### BEGIN /etc/grub.d/41_custom ###
if [ -f  ${config_directory}/custom.cfg ]; then
  source ${config_directory}/custom.cfg
elif [ -z "${config_directory}" -a -f  $prefix/custom.cfg ]; then
  source $prefix/custom.cfg;
fi
### END /etc/grub.d/41_custom ###

### BEGIN /etc/grub.d/50_huayra_color ###
# Huayra tweeks 
# 
set color_normal=dark-gray/black 
set color_highlight=white/cyan 
### END /etc/grub.d/50_huayra_color ###
ragnarok@ragnarok:/etc/grub.d$ 

```

Esto seteaba los colores de los textos de acuerto a un theme de grub de inicio, lo que problablemente hayq ue haces es hoy por hoy cambiar esos colores
