### ISSUE TITLE
Instalador mejorado para Flash Player

### ISSUE THREAD

**Issue by fermuch** [HuayraLinux/huayra-desktop#3]
En mi escuela, cuando probamos el Huayra, noté quejas sobre el instalador de Flash Player, que no te indica si se está instalando verdaderamente o no. También estaría bueno el añadir una nota para avisar al usuario de que **no es software libre**, para poder concientizarlo.

Me puse a ver un poco el código, y vi que es un script hecho con zenity, y por eso no hay menú que te diga "instalando".

Para poder solucionar esto, pasé el instalador a python, usando pygtk, y ahora la pantalla queda mientras se está instalando la aplicación.

Dependencias:
- python (2.7)
- pygtk

Repositorio: [huayra-flash-installer](https://github.com/fermuch/huayra-flash-installer)

Nota: no soy programador de aplicaciones de escritorio, así que si ven algún cambio o tienen algún consejo, háganme un pull request :smiley:

**Comment by ftoledo** [comment]
@Cierro ya que flash quedó obsoleto
