### ISSUE TITLE
Asociar paquetes deb a algun instalador de paquetes..

### ISSUE THREAD

**Issue by matiasdelellis** [HuayraLinux/huayra-desktop#30]
Antes usábamos gdebi, pero este no gestiona las dependencias..

![VirtualBox_EFI Test_19_07_2021_09_54_07](https://user-images.githubusercontent.com/733715/126165681-476292e6-d0d0-4c2a-8171-471a4910b353.png)

Después lo reemplazamos con gpk-install-local-file (Parte de gnome-packagekit) que funcionaba bien, pero la gente de gnome eliminaron esta funcionalidad en favor de gnome software. (https://gitlab.gnome.org/GNOME/gnome-packagekit/-/commit/83c6f8590a80333ccda56d727adb2bb13598b748?page=2)

Estoy trabajando en un fork de gnome-packagekit, pero devuelve esta funcionalidad entre otras, pero aun esta en desarrollo.

* https://github.com/matiasdelellis/xings-packagekit

**Comment by ftoledo** [comment]
Volvi a agregar gdebi ya que si gestion bien las deps, el problema era particular con screenruler que estaba en torbellino y no en austral.
De todas formas sigamos avanzando con xings para que sea una alternativa.
